### ISSUE TITLE
export React instead of Fuel

### ISSUE THREAD

**Issue by leecade** [brn/fuel#2]
Think about the real scene, as your design is React compatible. It's better to write code completely according to the React style. So some react-project painless switch to fuel don't need to modify import.

Only one change here:

```
// webpack.config.js
{
    resolve: {
        alias: {
            'react': 'fuel',
            'react-dom': 'fuel'
        }
    }
}
```

Glad to see increasing react-like framework available for replacement, above idea from a similar project: https://github.com/Lucifier129/react-lite

**Comment by brn** [comment]
@leecade 
Hey.
Now fuel is export React namespace same as Fuel and React namespace is completely same as Fuel.
Like this.
```
export const React = Fuel;
```

So you can use Fuel as React, but I'm still not tested replacing react with fuel.
